apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: {{ .Values.backend.service.type }}