apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
        {{- include "crud-app.labels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret
              key: MONGO_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: BACKEND_PORT
        ports:
        - containerPort: {{ .Values.backend.port }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}