apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
data:
  BACKEND_PORT: "{{ .Values.backend.port }}"
  FRONTEND_PORT: "{{ .Values.frontend.port }}"
  BACKEND_SERVICE_NAME: "{{ .Values.backend.service.name }}"