apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URL: {{ .Values.mongodb.url | b64enc | quote }}